catppuccin/nvim

- colors/soft_manilo.vim
- lua/catppuccino/color_schemes/soft_manilo.lua
Resolves: #18 
@Pocco81 feel free to make any edits required.
> add soft_manilo theme

- autoload/lightline/colorscheme/catppuccin.vim
- autoload/lightline/colorscheme/catppuccino.vim
> Fix lightline

- lua/catppuccin/core/integrations/treesitter.lua
I have added some missing TS colors and modified TSTagAttribute since it was pulling from TSProperty and for certain filetypes like tsx or jsx, it was providing too much red color and having hard contrast.
> Adding to TreeSitter colors

- lua/catppuccin/core/color_palette.lua
- lua/catppuccin/core/integrations/gitsigns.lua
- lua/catppuccin/core/integrations/indent_blankline.lua
- lua/catppuccin/core/integrations/treesitter.lua
- lua/lualine/themes/catppuccin.lua
Created individual comments per file.
Open to tweak anything as we see fit.
> Tweaking some colors as discussed in Discord

- lua/catppuccin/core/integrations/ts_rainbow.lua
> fix(ts-rainbow-background): fix guibg highlight

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/core/integrations/neotree.lua
Added highlight groups for Neo-tree (https://github.com/nvim-neo-tree/neo-tree.nvim) Based the colors off of what is used for nvim-tree
> Added neo-tree highlighting

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/core/integrations/symbols_outline.lua
Add support for https://github.com/simrat39/symbols-outline.nvim
> Add highlighting for Symbols-Outline plugin

- lua/catppuccin/core/integrations/lightspeed.lua
> fix:#153 after_loading callback recursive execute

- lua/catppuccin/core/integrations/bufferline.lua
> fix: bufferline integration w transparent_background

- lua/catppuccin/core/mapper.lua
PR for adding highlight for WinBar as . mentioned in #148 :smiley:
> Adding Highlighting for WinBar as of #148

- lua/catppuccin/core/integrations/native_lsp.lua
Fixes #160 . This is my first PR :)
> fix: native_lsp highlights in sign column #160

- lua/catppuccin/config.lua
- lua/catppuccin/core/integrations/leap.lua
> feat: add leap support

- .github/workflows/formatting.yaml
Also, please `stylua .` the entire project :)
> ci(github): Add stylua check

- README.md
dim_inactive seems to be incorrectly explained and example provided in README.
It could mislead many people since it does result in a broken config.
> clarify and fix README description of dim_inactive in config

- lua/catppuccin/groups/integrations/lightspeed.lua
- lua/catppuccin/lib/hsluv.lua
- lua/catppuccin/utils/colors.lua
mocha
macchiato
frappe
latte
Closes #5
> integration(lightspeed): follow guidelines

- lua/catppuccin/groups/integrations/leap.lua
> fix(integration): Match leap.nvim guidelines

- lua/catppuccin/groups/syntax.lua
> fix(syntax): DiffAdd/DiffDelete consistency

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/groups/integrations/overseer.lua
Feel free to change any colors you see fit :)
> Adding overseer.nvim support

- lua/catppuccin/groups/integrations/overseer.lua
There was another one missing... :'(
> fix: Missing fg key in color definition

- lua/catppuccin/groups/integrations/feline.lua
I made each icon in the feline bar an option in the assets, so that users can change all of the icons to whatever they want.
> Added more asset options to the feline bar

- lua/catppuccin/groups/integrations/ts_rainbow.lua
Removing unnecessary background highlighting since parenthesis should always have same background as the current background by default.
Before:
After:
> Fix: TS-Rainbow

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/groups/integrations/fidget.lua
- lua/catppuccin/groups/integrations/treesitter_context.lua
> feat: Add fidget.nvim integration

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/pounce.lua
[Pounce](https://github.com/rlane/pounce.nvim) is a motion plugin which can do incremental fuzzy search. Here are pictures show the final result.
before:
after:
> Add pounce.nvim integration

- lua/catppuccin/lib/compiler.lua
> fix: CatppuccinCompile complains directory already exists. Closes #281

- lua/catppuccin/groups/integrations/neotree.lua
> fix(neotree): better highlighting experience

- lua/catppuccin/groups/integrations/fidget.lua
> fix: update fidget.nvim title highlight color

- lua/catppuccin/groups/editor.lua
- lua/lualine/themes/catppuccin.lua
> fix(statusline): respect transparent background

- lua/catppuccin/groups/editor.lua
- lua/lualine/themes/catppuccin.lua
> fix(float window): respect transparent background

- README.md
- lua/catppuccin/groups/integrations/mason.lua
> feat(integrations): add mason.nvim

- lua/catppuccin/groups/editor.lua
> fix(folded): respect transparency

- lua/catppuccin/groups/editor.lua
- lua/catppuccin/groups/integrations/telescope.lua
telescope selection and Pmenu respect transparency
> fix(transparency): telescope selection and Pmenu respect transparency

- README.md
- colors/catppuccin-frappe.lua
- colors/catppuccin-latte.lua
- colors/catppuccin-macchiato.lua
- colors/catppuccin-mocha.lua
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/bufferline.lua
- lua/catppuccin/groups/integrations/feline.lua
- lua/catppuccin/groups/integrations/treesitter.lua
- lua/catppuccin/init.lua
- lua/catppuccin/lib/compiler.lua
- lua/catppuccin/lib/mapper.lua
- lua/catppuccin/palettes/init.lua
- lua/catppuccin/utils/colors.lua
> feat: Respect o:background

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/noice.lua
I think the default list is already pretty good tho
Closes #302
> feat: Add noice.nvim integration

- lua/catppuccin/groups/integrations/native_lsp.lua
add DiagnosticFloating & DiagnosticSign highlight
> fix(diagnostic): add floating and sign highlight

- README.md
- lua/catppuccin/groups/integrations/bufferline.lua
The example in readme is set no italic .
> fix(bufferline): Respect gui styles

- after/queries/css/highlights.scm
- lua/catppuccin/groups/integrations/treesitter.lua
> feat(treesitter): Improve css highlights

- lua/catppuccin/groups/integrations/leap.lua
> fix(leap): respect transparency

- lua/catppuccin/groups/editor.lua
NormalFloat bg respect transparency
> fix: NormalFloat bg respect transparency

- lua/catppuccin/init.lua
cc @stasjok #352
I will also look into the re-compile issue, sorry..
> fix(compile): .git doesn't exist on nixos

- lua/catppuccin/init.lua
Related #352 
Removed the dreadful date checking
> fix(compile): simplified caching method

- lua/catppuccin/lib/hashing.lua
- lua/catppuccin/lib/native_bit.lua
Undefined behavior on arm because of float overflow
> fix(compile): bit on aarch64

- lua/catppuccin/groups/editor.lua
Hi there!
Just a small mistake in the notes.
> fix(editor): remove outdated comment

- lua/catppuccin/groups/integrations/dap.lua
> feat(dap-ui): add control hl group

- lua/catppuccin/groups/syntax.lua
> fix(syntax): debugPC respect transparency

- lua/catppuccin/lib/compiler.lua
> fix(compile): invalid cterm

- lua/catppuccin/lib/compiler.lua
> Revert "fix(compile): invalid cterm"

- lua/catppuccin/groups/integrations/dap.lua
Noticed this old variable name while working on my previous PR
> fix(dap-ui): rename old color reference

- .github/workflows/neovim.yml
- .github/workflows/tests.yml
https://github.com/dundargoc/neovim/commit/fc1e2d897cd22e5f2ba13aa369294e8630a196a6
> ci: fix failing neovim tests on ubuntu

- lua/catppuccin/groups/integrations/feline.lua
> feat(feline): match background colors to other similar plugins

- .github/workflows/neovim.yml
- .github/workflows/tests.yml
- .github/workflows/vim.yml
https://github.com/catppuccin/nvim/pull/453#discussion_r1167366086
> ci: simplify "pull_request" keys

- lua/catppuccin/groups/integrations/lsp_trouble.lua
> fix(lsp_trouble): TroubleNormal/TroubleCount transparency

- README.md
- doc/catppuccin.txt
- lua/barbecue/theme/catppuccin.lua
- lua/catppuccin/init.lua
https://github.com/catppuccin/nvim/issues/462#issuecomment-1515612974
> feat(barbecue): add `alt_background` integration setting

- lua/catppuccin/groups/integrations/bufferline.lua
> fix(bufferline): fix selected tab separator highlight group

- lua/catppuccin/groups/integrations/gitsigns.lua
- lua/catppuccin/groups/integrations/native_lsp.lua
- lua/catppuccin/groups/integrations/neotree.lua
respect transparency for word diff in preview
> fix(gitsigns): respect transparency

- README.md
- doc/catppuccin.txt
- lua/catppuccin/init.lua
- lua/catppuccin/lib/compiler.lua
- lua/catppuccin/lib/vim/compiler.lua
- vim.yml
> feat: `no_underline` option

- lua/catppuccin/types.lua
Updates types for the dropbar integration added in #499
> chore: update types

- lua/catppuccin/groups/integrations/feline.lua
> fix(feline): use new `vim.lsp.status()` method

- README.md
The original feline plugin repository has been archived and the new URL is the official new home.  The original author chose not to transfer ownership of the repository to the new maintainer.
- If it's your first time contributing to a project then read [About pull …
> docs(README): update feline.nvim url

- README.md
> Correct typo in custom_highlights section of README

- lua/catppuccin/groups/integrations/native_lsp.lua
> feat(native_lsp): support inlay hints

- lua/catppuccin/groups/integrations/telescope.lua
Just borrowed several highlights from the original integration :)
> fix(telescope): keep consistency between the two styles

- lua/catppuccin/groups/integrations/treesitter.lua
- lua/catppuccin/groups/syntax.lua
> refactor(syntax): respect style guide part 2

- lua/catppuccin/groups/integrations/telescope.lua
> fix(telescope): respect transparency

- lua/catppuccin/groups/integrations/noice.lua
> fix(noice): set background blend to 0 for mini popups

- README.md
- doc/catppuccin.txt
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
> Revert integration_default

- lua/catppuccin/types.lua
> fix(types): make all options besides nested `enabled` optional

- README.md
- doc/catppuccin.txt
- lua/catppuccin/init.lua
- lua/catppuccin/palettes/init.lua
- lua/catppuccin/types.lua
- vim.yml
> feat: add workaround for kitty transparent issue

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/indent_blankline.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
- vim.yml
Updated [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim) to support their latest version.
Added feature to let users choose what color they want for their scope indent line.
Fixes #583
> feat(indent-blankline): update to v3, add scope color

- lua/catppuccin/groups/integrations/dashboard.lua
> feat(dashboard): add highlight groups for `doom` theme

- lua/catppuccin/groups/integrations/flash.lua
> fix(flash): link `FlashPrompt` to `NormalFloat`

- lua/catppuccin/groups/integrations/neotree.lua
> fix(neotree): change color of untracked files

- lua/catppuccin/groups/integrations/neogit.lua
Added missing neogit highlight groups.
> feat(neogit): support new highlight groups

- lua/catppuccin/groups/integrations/neogit.lua
> fix(neogit): remove `NeogitCursorLine` from integration

- lua/catppuccin/groups/integrations/neogit.lua
NeogitDiffContext background was set to lavender which does not look nice.
Changed it to base.
> fix(neogit): tweak diff context highlighting

- README.md
- doc/catppuccin.txt
- lua/catppuccin/types.lua
Fixed special setup according to https://github.com/j-hui/fidget.nvim/blob/main/doc/fidget.md#options
> docs(fidget.nvim): `window.blend` -> `notification.window.winblend`

- lua/catppuccin/groups/editor.lua
> fix: sync focused and unfocused winbars

- lua/catppuccin/groups/integrations/notify.lua
> feat(notify): add `NotifyBackground` hl group

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/symbols_outline.lua
> feat: add support for `outline.nvim` plugin

- README.md
- lua/catppuccin/utils/reactive.lua
- lua/reactive/presets/catppuccin-frappe-cursor.lua
- lua/reactive/presets/catppuccin-frappe-cursorline.lua
- lua/reactive/presets/catppuccin-latte-cursor.lua
- lua/reactive/presets/catppuccin-latte-cursorline.lua
- lua/reactive/presets/catppuccin-macchiato-cursor.lua
- lua/reactive/presets/catppuccin-macchiato-cursorline.lua
- lua/reactive/presets/catppuccin-mocha-cursor.lua
- lua/reactive/presets/catppuccin-mocha-cursorline.lua
Hi there! Made an integration for `reactive.nvim` plugin.
> feat(integration): add reactive.nvim integration

- README.md
- doc/catppuccin.txt
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
Add capability to ignore default integrations
---
Closes #686
> feat: add ability to toggle default integrations

- lua/catppuccin/types.lua
> fix(illuminate): update type

- README.md
- doc/catppuccin.txt
- lua/catppuccin/init.lua
- lua/catppuccin/lib/compiler.lua
Hopefully f i x #682
Special thanks to @Jint-lzxy for the idea
> fix(flavour): respect terminal's background

- lua/catppuccin/groups/integrations/treesitter_context.lua
> feat(treesitter-content): highlight line number

- lua/catppuccin/groups/integrations/bufferline.lua
> feat(bufferline): add `indicator_visible` and `modified_visible`

- lua/catppuccin/groups/integrations/feline.lua
Fix a typo in feline.lua file. runing -> running
> fix(feline): fix typo

- lua/catppuccin/palettes/init.lua
> fix(kitty): respect `transparent_background` option

- lua/catppuccin/palettes/init.lua
> revert: fix(kitty): respect `transparent_background` option

- README.md
Add installation instruction for [mini.deps](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-deps.md) plugin manager.
> docs(README): add installation instruction for mini.deps

- lua/catppuccin/groups/integrations/blink_cmp.lua
> feat(blink-cmp): add Copilot kind support

- lua/catppuccin/utils/reactive.lua
Add a more prominent cursor color to the reactive integration.
> feat(reactive): add cursor color for normal mode

- README.md
- lua/catppuccin/groups/integrations/signify.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
Use the same highlights as for gitgutter / gitsigns.
> feat(signify): add vim-signify integration

- lua/catppuccin/groups/integrations/markview.lua
> fix(markview): adjust highlights

- lua/catppuccin/init.lua
still use default settings when integrations are off by default
fixes #763
> fix: adjust default integration settings

- lua/catppuccin/groups/integrations/octo.lua
> fix(octo): clear `OctoFilePanelFileName` hl group

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/snacks.lua
- lua/catppuccin/types.lua
> feat(snacks): add nvchad style for snacks.picker

- lua/catppuccin/groups/editor.lua
> fix(editor): use `PmenuSel` bg for `PmenuExtraSel`
