catppuccin/nvim

- lua/lualine/themes/catppuccino.lua
cpt.red_bg does not exist, it probably was meant to be cpt.red_br.
> Fix typo in lualine theme replace mode

- README.md
- lua/catppuccino/config.lua
- lua/catppuccino/core/integrations/hop.lua
Defined colors for hop.nvim
Default hop colors  (with dark_catppuccino) :
After this commit
dark_catppuccino:
soft_manilo
neon_latte
light_melya
In my opinion these colors look good in the dark themes, but not so good in light_melya.  Is it possible to define different colors only for light_melya?
> Define hop colors

- autoload/lightline/colorscheme/catppuccino.vim
This fixes the issue where lightline complains it can't find the catppuccino colorscheme.
The colorscheme must be stored in a global variable that lightline expects.
> Fix lightline not finding colorscheme

- lua/catppuccino/core/integrations/native_lsp.lua
add support for neovim head diagnostics bcz of this commit
https://github.com/neovim/neovim/commit/2e8103475e18d1e4aa0d6355107f393815a886a6
> vim.lsp.diagnostic has been moved to vim.diagnostic

- lua/katppuccino/core/mapper.lua
With the refactor removing values from the color mapper table,
the missing value on cp.none prevents transparency from being
respected.  This adds a value for that in a core.mapper close
to where it is used and does not pollute th color mapping table.
> Respect transparency by providing a value for cp.none

- README.md
With the organization switch & split to app-specific repos, a few of the
README links become outdated. This PR:
- Updates those links to point to the correct repo for each application
- Adds links to termux & xresources
- Orders the links (alphabetically)
I took some liberties with the organization/content; if you'd like me to make
changes or make this PR smaller I'd be happy to break it down into smaller
PRs for discussion around each integration.
You can preview this PR [here](https://github.com/jaydorsey/nvim/tree/jay/readme_updates#special-integrations), but here's a screenshot also:
> README link updates

- lua/catppuccin/core/integrations/treesitter.lua
This highlight is actually not recommended by tree-sitter to have it active.
Additionally, it provides errors with certain parsers and examples such as styled components in jsx / tsx
Referring to gh issue discussing related issue over on nvim-treesitter:
https://github.com/nvim-treesitter/nvim-treesitter/pull/1628#issuecomment-997002440
> removing TSError highlight

- lua/catppuccin/core/integrations/gitgutter.lua
- lua/catppuccin/core/integrations/neogit.lua
- lua/catppuccin/core/mapper.lua
As per issue #75  , all add related highlights could be implemented as green color since it is fairly standard
> setting all git add related highlights to green as standard

- lua/catppuccin/core/integrations/gitsigns.lua
It seems that a misnaming of `cnf.transparent_background` caused the background of `GitSigns*` colour groups to not be appropriately highlighted with a transparent background set.
> fix: gitsigns transparent background

- lua/catppuccin/core/integrations/ts_rainbow.lua
When setting nvim-ts-rainbow highlight groups, do not set a background highlight if  is
> fix(ts-rainbow): respect transparent_background

- lua/catppuccin/core/integrations/neogit.lua
Change background color in neogit integration. Use a slightly more light color than the background instead of a very light color. Headers are more light, but only slightly.
Added and Removed lines also gets background highlight matching to make it more obvious which hunk you are acting on.
See videos for changes.
https://user-images.githubusercontent.com/1599/149591064-d9a403a8-5144-420a-98e6-47871372079e.mp4
https://user-images.githubusercontent.com/1599/149591066-061bb2e9-5039-48d4-ac1c-1b36f851bb7a.mp4
References #75.
> Improve background colors in neogit integration

- lua/lightline/colorscheme/catppuccin.lua
This improves the legibility of the right side of lightline. The rightmost section matches an existing color combination in multiple other components. The second-to-rightmost component background has a small shade lightening to distinguish it from the rightmost component.
Currently on `main`:
With these changes:
> Improve legibility of right side of lightline.

- lua/catppuccin/core/integrations/nvimtree.lua
Seems like a typo was causing this feature (#98) to not work as expected
> fix: nvimtree integration transparent panel

- lua/lualine/themes/catppuccin.lua
This PR improves the visibility of horizontal splits when using the supplied lualine theme.
Here's the "before" (how it is right now):
It's really hard to tell that there is an horizontal split here, right?
And here's the "after" (how it is in the PR):
It looks much clearer, IMHO.
> 💄Lualine theme: Improve horizontal split visibility

- lua/catppuccin/core/integrations/feline.lua
Attempting to use the feline integration resulted in an error message when `winid` was `nil`. This pr contains the following changes:
* Applying stylua formatting
* Added helper function `is_enabled` that ensures winid is always a Lua number
* Replacing blocks setting the `enabled` attribute with calls to the new `is_enabled` helper function.
Let me know if the styling or naming should be tweaked.
> fix: Handle nil winid values in feline integration

- README.md
The feline integration needs the kyazdani42/nvim-web-devicons plugin to function properly,
therefore the reader should be warned about the requirement.
> README added requirement notice to feline integration section

- README.md
As explained in #126, `'glepnir/lspsaga'` does not seem to be maintained anymore with its last commit over 12 months ago and many bugs. `'tami5/lspsaga'` is a well-maintained fork with exactly the same settings and config that people should be pointed towards.
Closes #126
> docs: Point towards fork 'tami5/lspsaga' instead of 'glepnir/lspsaga'

- README.md
Back in the day flavour names were changed and now there's no `dusk` flavour anymore
> fix: flavour naming in README.md

- README.md
- lua/catppuccin/core/integrations/mini.lua
Hi! I would like to add explicit support for [mini.nvim](https://github.com/echasnovski/mini.nvim).
Basic choices are taken from either highlight groups to which 'mini.nvim' makes default links or from analogous plugins.
Differences from default linked groups:
- 'mini.indentscope' is based on 'indent_blankline.lua'.
- 'mini.jump' is based on 'vim_sneak.lua'.
- 'mini.jump2d' is based on 'hop.lua'.
- 'mini.starter' is based on 'dashboard.lua', 'which_key.lua', and personal choices:
- `MiniStarterInactive` is same as comments.
- `MiniStarterItemBullet` is blue as borders.
- `MiniStarterQuery` is green to be opposite of pink item's prefix.
- `MiniStarterSection` is flamingo to be visible.
- 'mini.statusline' is based on 'lualine/themes/catppuccin.lua' and personal choices:
- …
> Add explicit support for 'mini.nvim'

- README.md
- lua/catppuccin/core/integrations/lightspeed.lua
- lua/catppuccin/main.lua
When we have a lot of 3rd party plugins, everyone will do a hook and wrap what's already there, it's too complicated.
why not use events?
> use autocmd event instead of after_loading hook

- lua/catppuccin/config.lua
- lua/catppuccin/core/integrations/telescope.lua
- lua/catppuccin/utils/util.lua
It bothered me that the telescope popup blended in with the background, especially if you remove the borders. In addition, I've added the ability to add custom highlights in the config, in case similar issues to this exist.
> tweaked telescope colors and added custom highlights

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/core/palettes/init.lua
This PR proposes a simple way to override the palette colors by setting the global variable `vim.g.catppucin_override_colors`.
Usage:
```lua
vim.g.catppuccin_flavour = "mocha"
vim.g.catppuccin_override_colors = {
base = "#ff0000"
}
vim.cmd [[colorscheme catppuccin]]
```
> Support overriding colors using vim.g.catppuccin_override_colors

- lua/catppuccin/core/integrations/indent_blankline.lua
I downloaded neovim 0.5 appimage and blend has always been integer value. No idea why is `nocombine` from `cterm` is here
Closes https://github.com/catppuccin/nvim/issues/173
> fix(highlight): Fix blend option

- lua/catppuccin/core/integrations/bufferline.lua
- lua/catppuccin/core/integrations/hop.lua
- lua/catppuccin/core/integrations/mini.lua
- lua/catppuccin/core/integrations/treesitter.lua
- lua/catppuccin/core/mapper.lua
- lua/catppuccin/utils/data.lua
- lua/catppuccin/utils/util.lua
Related: https://github.com/catppuccin/nvim/issues/169
legacy `vim.cmd`
```
014.030  000.077  000.077: require('catppuccin')
014.077  000.045  000.045: require('catppuccin.config')
014.257  000.041  000.041: require('catppuccin.utils.util')
014.260  000.090  000.049: require('catppuccin.main')
014.448  000.050  000.050: require('catppuccin.utils.hsluv')
014.451  000.147  000.097: require('catppuccin.utils.colors')
014.547  000.027  000.027: require('catppuccin.utils.echo')
014.549  000.061  000.034: require('catppuccin.core.palettes.init')
014.615  000.063  000.063: require('catppuccin.core.palettes.mocha')
014.666  000.031  000.031: require('catppuccin.core.palettes.latte')
014.668  000.215  000.060: require('catppuccin.lib.ui')
014.669  000.407  000.045: …
```
> refactor(performance): Improve nvim_set_hl

- lua/catppuccin/groups/integrations/feline.lua
This PR contains the following proposal:
- add a bar character to the end of the git component in order to have consistent spacing
- add a label to the Lsp server icon in order to have an indication of what the icon represents
- change the spaces in the git icon in order to have consistent spacing
With no separator:
fix: ![fix_feline_no_separator](https://user-images.githubusercontent.com/3298487/182427869-239cb6b6-492c-4773-b5ca-d71aad76ab4a.png)
no_fix: ![nofix_feline_no_separator](https://user-images.githubusercontent.com/3298487/182427904-c8997607-4a0f-43a0-82bb-b2848c9d08dd.png)
With separator:
fix: ![fix_feline_with_separator](https://user-images.githubusercontent.com/3298487/182428009-6004df2b-4e45-4426-b4e2-9ae5c4b24321.png)
no_fix: …
> fix(feline): fix spacing between components, add label for Lsp indicator

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/groups/integrations/navic.lua
I added support to nvim-navic... I've tried to base the colors on the cmp and on treesitter. 
One issue that I'm not sure how to solve is the background. I thought putting `NONE` on all of them would make it transparent, but it is not happening, when I set it in lualine for example I'm getting the `base` background instead. Perhaps you could point me to how to solve this :)
> Adding support to nvim-navic

- lua/catppuccin/groups/integrations/neogit.lua
> fix(neogit): improve Neogit colors

- lua/catppuccin/groups/integrations/feline.lua
In feline integration is not set an option for inactive components.
The problem is, that you don't know what other split-windows are. To explain it better see the following screenshot.
This shows the DAP-UI. Here is set `laststatus = 3` 
You don't know where the *scopes*, the *breakpoint*, the *wathes* and so on they are.
By switching the split-windows you see only a black bar on the bottom.
https://user-images.githubusercontent.com/39212564/186997584-e3431164-968e-4712-a49c-80caf92aa831.mov
With `laststatus = 2` you have in every split-window a black bar at the bottom.
With the inactive component in feline, it looks like this...
Here is set `laststatus = 2`...
You see exactly where what is
With `laststatus = 3` you see what split-window is in the bottom, by switching the pane... …
> Adding inactive component to feline

- README.md
- lua/catppuccin/config.lua
- lua/catppuccin/groups/integrations/treesitter_context.lua
> feat: Add nvim-treesitter-context integration

- .editorconfig
Changes `indent_style = tabs` -> `indent_style = tab` since "tabs" isn't possible value for indent_style as stated here: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style.
> Fix: editorconfig

- README.md
Right now, I think the integrations are listed in chronological order in which support was added in catppuccin-nvim. As a user, I think it's easier to look through the integrations in alphabetical order, especially if you're new to the colorscheme, and wondering, "Does this support my favorite plugins?"
> chore(readme): Sort integrations in alphabetical order.

- lua/catppuccin/groups/integrations/which_key.lua
Hi, catppuccin/nvim!
A new highlight group has been added to `which-key.nvim`.  (https://github.com/folke/which-key.nvim/commit/9c190ea91939eba8c2d45660127e0403a5300b5a)
This PR adds a new group and further removes unnecessary duplication.
> Add `WhichKeyBorder` highlight group

- .github/workflows/formatting.yml
This commit fixed the problem with formatting CI. Currently incorrect artifact was chosen due to the introduction of `linux-aarch64` artifacts of latest `stylua-action` _(a.k.a, `v1.1.0`)_, which would cause "ELF not found" related errors.
> Ref: https://github.com/JohnnyMorganz/stylua-action/releases/tag/v1.1.1
> fix(CI): Broken formatting workflow (ELF not found).

- .editorconfig
Restores .editorconfig with the following changes
- Remove indent size
- Mandate tabs only for lua
> style: restore .editorconfig

- lua/catppuccin/groups/integrations/treesitter.lua
https://github.com/catppuccin/nvim/commit/bb805c5fd6149b62e64861f13caa85b40d279a44 broke highlighting for ruby symbols. 
This is because in tree-sitter integration there were no support for ruby symbols.
- Before
- After
> feat(treesitter): add highlighting for ruby symbols

- lua/catppuccin/groups/integrations/neotree.lua
> fix(neotree): better popup style in transparent background

- README.md
macOS's "Terminal.app" does not support TrueColor. It can be tricky to identify
what's going wrong when users encounter this issue. Hopefully this will point
them in the right direction by identifying that Terminal.app doesn't have the
color support that catppuccin requires.
> Add FAQ Section for TrueColor

- lua/catppuccin/groups/integrations/bufferline.lua
> fix(bufferline): Display separator on transparent background 

- lua/catppuccin/groups/integrations/bufferline.lua
renderings:
Frappe
transparency
> fix(bufferline): add tab separator highlight

- lua/catppuccin/groups/integrations/feline.lua
Feline added new providers for macro recordings and search count.
This is useful if `cmdline=0`. By pressing `qa...` it's shows the recording next to the *position* component. Same for the search count. 
If you don't like the position of the two components, feel free to position them elsewhere.
> Added Felines new provider: macro and search count

- lua/catppuccin/groups/integrations/native_lsp.lua
Fix the LspInfo border color.
Before:
After:
> fix(lsp): LspInfo border color

- lua/catppuccin/groups/editor.lua
- lua/catppuccin/groups/integrations/mini.lua
Hi, I made this pr for better `mini.tabline` integration. This will add **underline** under current buffer, also I added some small fixes related to background which look quite off to the colorscheme.
Thank you!
> feat(mini.nvim): better tabline integration with underline support

- lua/catppuccin/groups/editor.lua
Related: https://github.com/catppuccin/nvim/pull/338#pullrequestreview-1178428569
> fix(mini.nvim): incorrect TabLineSel color

- lua/catppuccin/init.lua
- lua/catppuccin/lib/vim/init.lua
cc @EdenEast
1. Hash user and git file name when `mtime = 1` (Which means nix is presented)
2. viml's getftime is faster than uv.fs_stat
```lua
local now = vim.loop.hrtime
local start = now()
for _ = 1, 10000 do
vim.fn.getftime "/home/nullchilly/.cache/nvim/catppuccin/date.txt"
end
print("getftime  " .. (now() - start) / 1000000 .. "ms")
start = now()
for _ = 1, 10000 do
vim.loop.fs_stat "/home/nullchilly/.cache/nvim/catppuccin/date.txt"
end
print("luajit    " .. (now() - start) / 1000000 .. "ms")
```
```lua
getftime  7.314094ms                                                                           
luajit    16.374475ms
```
Closes #348
> fix(nix): no longer stuck in 1969

- lua/catppuccin/groups/integrations/treesitter.lua
Ever since [this commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/0f866c15b4e77406c3eb4110e7ddbabce52ccaa1) in treesitter's git repo. The colors in my PHP files look off. Private / protected / public keywords in classes are now yellow and do not really fit its surrounding colors. I am not sure if this yellow is the intended color for Catppuccin's theme, because if I look at examples / images these keywords are usually pink; for example in [this image](https://preview.redd.it/2zwg74ym3n381.png?width=1327&format=png&auto=webp&s=f2a4e2f466be53bed6deee97de0831b452863a0a). Pink fits better, because it will not make these keywords stand out as much.
I have the impression that this pink color is the intended one for these keywords. If I am mistaken and the keywords are yellow on …
> Fix: @type.qualifier color pink according to examples

- lua/catppuccin/groups/integrations/symbols_outline.lua
Looks nicer when cursorline is set.
Before:
After:
> fix(symbols_outline): remove FocusedSymbol bg

- lua/catppuccin/groups/integrations/neotest.lua
Original neotest's theme:
Current catppuccin integration:
With this PR:
> fix(neotest): consistency with original theme

- lua/lualine/themes/catppuccin.lua
The default color of the `terminal` mode in lualine is the same as the `normal` mode,
specify a color for the terminal mode to recognize whether the mode is either `terminal`
or `normal`.
> feat(lualine): add a specific color for the terminal mode

- lua/catppuccin/groups/integrations/nvimtree.lua
The `NvimTreeVertSplit` highlight group has been deprecated in favor of `NvimTreeWinSeparator`, more about this: https://github.com/nvim-tree/nvim-tree.lua/pull/1225
When used this highlight group with `transparent_background = false` there is a line next to NvimTree:
With the changes of this PR it looks like this:
> fix(nvimtree) replace deprecated highlight-group

- lua/catppuccin/lib/compiler.lua
This fixes an error in neovim v0.9:
bad argument #4 to 'fmt' (string expected, got boolean)
- If it's your first time contributing to a project then read [About pull requests](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/a …
> Explicitly convert value to string

- lua/catppuccin/groups/integrations/lsp_trouble.lua
uh, just a little fix highlight group names
**before**: 
**after**:
> fix(lsp_trouble): incorrect highlight group names

- lua/catppuccin/groups/integrations/neogit.lua
add [notification highlighting](https://github.com/TimUntersberger/neogit#notification-highlighting) for neogit, same color as [notify](https://github.com/rcarriga/nvim-notify) integration.
before(info notification has inconsistent green color):
after:
> feat(neogit): add notification highlight groups

- README.md
- lua/barbecue/theme/catppuccin.lua
- lua/catppuccin/init.lua
Coincidentally I found #376  after finishing it,
However, there are some differences between mine and his. 
The main difference is that I use Conceal for the file path and it uses Normal,
which is a part that is unique to barbecue and not available in navic.
> feat(barbecue): add barbecue

- README.md
Some special integrations are hidden in the README due to a small typo, this fixes it.
> fix hidden special integrations in README.md

- lua/catppuccin/init.lua
Tested:
- Set colorscheme when g:colors_name is present (Hence the lock check)
- whether g:colors_name == "catppuccin" initially
- Respect o:background
- Change flavour
- Respect User default flavour
Resolve: https://github.com/catppuccin/nvim/pull/380
> fix(load): flavour mechanism

- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/lsp_saga.lua
This commit makes `catppuccin` compatible with `lspsaga`@v0.2.4. It added support for the latest highlight groups.
Major highlight groups have been adapted to stay harmonic with other integrations _(to the best of my ability)_. The default values for some highlight groups are just ok, so I didn't append them to the list.
<sup>Minor fixes:</sup>
<sup>\* Custom colors are no longer supported, so they have been removed.</sup>
> feat(lspsaga): Add support for latest highlight groups

- README.md
- lua/catppuccin/groups/integrations/sandwich.lua
Hello,
This is a simple but vital sandwich integration ^^
The highlights are very subtle and invisible on the cursor line.
In my opinion one color is enough for all groups so I've chosen the blue, is it ok ?
> feat: add vim-sandwich integration

- lua/catppuccin/groups/editor.lua
- lua/catppuccin/groups/integrations/noice.lua
- lua/catppuccin/groups/integrations/which_key.lua
- lua/catppuccin/init.lua
- lua/catppuccin/lib/vim/compiler.lua
- lua/catppuccin/lib/vim/init.lua
fix #401
With `vim.o.winblend = 0` and `vim.o.pumblend = 0` (default value in neovim):
With `vim.o.winblend = 50` and `vim.o.pumblend` = 50:
> fix(transparent): winblend and popup

- lua/catppuccin/groups/integrations/treesitter.lua
I noticed a few weeks ago that my php theme changed. The methods in my classes became peach colored. I found out this change happened in [this commit](https://github.com/robmeijerink/nvim/commit/b17cfa01cf0517cc3614602df39e8433dc116fab). I figured this is by mistake, because [this reference](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/syntax.lua#L14) states that method calls should have the same colors as functions. I restored the colors of methods in this PR to how they were before. I checked the rest of my php syntax and all the colors are back to normal again. Thanks for this great theme!
> Fix: php theme methods

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/ts_rainbow2.lua
- lua/catppuccin/init.lua
[nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow)  is no longer maintained.
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) recommend [nvim-ts-rainbow2](https://github.com/HiPhish/nvim-ts-rainbow2) in its wiki [Extra modules and plugins](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Extra-modules-and-plugins).
So, I add support for it based on nvim-ts-rainbow
> feat(nvim-ts-rainbow2): add support for ts-rainbow2

- lua/catppuccin/lib/compiler.lua
- lua/catppuccin/lib/vim/compiler.lua
This pr cleans up the compiler and removes the requirement to save the compiled file to `require('catppuccin').compiled` and read back again.
> fix(compiler): remove `require` call to write compiled files

- lua/catppuccin/lib/hashing.lua
Problem: `{ string.byte }` is only faster if we re-use the table a lot
Solution: Remove table caching
| method | time |
| ------ | ---- |
| old | 0.3883049273 |                                                                                  
| new | 0.0047219172 |
> feat(compile): remove table overhead for better performance

- lua/catppuccin/init.lua
- lua/catppuccin/lib/compiler.lua
- lua/catppuccin/lib/vim/compiler.lua
- If `g:colors_name` was set then `:set background=dark/light` will trigger `ColorScheme` autocmd. We can replace the `lock` mechanism simply by setting `o:background` before `g:colors_name`
- We compiled to bytecode using `string.dump(f)` and then load with `loadstring(str, "=")` to strip the debug infos. A better way (to save binary size) would be `string.dump(f, true)` which strip the debug info and then load with `loadstring(str)`
- `local h = nvim.api.nvim_set_hl` was introduced to further strip the bytecode size.
> fix(load): remove o:background reload workaround

- lua/catppuccin/groups/integrations/semantic_tokens.lua
- lua/catppuccin/init.lua
Highlighting on nightly is **broken** right now, because of neovim/neovim#22022.
This PR is basically just recent commits from folke/tokyonight.nvim.
This needs to be tested, bc I'm not sure if I didn't break anything.
> feat: add support for new lsp semantic token highlight groups

- lua/catppuccin/groups/editor.lua
Since rainbow parentheses are widely used, I highly recommend changing the `bg` for `MatchParen`, so that the highlight is better able to distinguish from rainbow colors.
before
after:
> feat(editor): better matchparen highlight

- lua/catppuccin/groups/editor.lua
I finally found that it was not so useful to change the `fg` after changing the `bg`,
and there are some advantages to removing the `fg`.
for example, it will not change the color of comments.
and when you use rainbow plugins, the color of the paratheses will not be changed easily.
> feat(editor): adopt matchparen highlight

- lua/catppuccin/groups/editor.lua
Reverts catppuccin/nvim#430
I found out that normal bracket has grey fg over grey MatchParen bg isn't a good fit
This fits more
> fix(editor): revert matchparen highlight

- lua/catppuccin/init.lua
With lazy.nvim each plugin's repo is in Detached HEAD which means there's no `.git/ORIG_HEAD`
Cache the `.git` folder modification date instead
> fix(setup): ORIG_HEAD doesn't exist in Detached HEAD

- lua/catppuccin/groups/integrations/headlines.lua
5f6b5b29 introduced support for lukas-reineke/headlines.nvim, this changes a few of the highlights.
- sets the background to a neutral surface0 for Headlines
- sets their respective foreground colors
- sets the foreground for Dashes to a more neutral overlay2
- links Quote to "@text.strong"
- link "Headline" to "Headline1" in case there is no headline hierarchy for the current parser
Which fixes the concerns mentioned in https://github.com/catppuccin/nvim/issues/433#issuecomment-1481073933
> feat: tweak headlines integration highlights

- lua/catppuccin/groups/integrations/treesitter_context.lua
> fix(nvim-treesitter-context): make `TreesitterContext` more readable when using `transparent_background` option

- lua/barbecue/theme/catppuccin.lua
I suggest to set the same background color for winbar (barbecue), as statusline (lualine) has, for consistency:
I looked at VSCode, status line has the same color as tab line has and context line is slightly brighter than both, but darker than regular text background. Maybe the color of winbar or statusline should be changed to another color or adjusted to VSCode colors.
> fix(barbecue): apply same bg as statusline has

- after/queries/javascript/highlights.scm
Enable highlight override for `["@keyword.export"]` in `js` and `mjs` files
Fix for #466
> feat(treesitter): enable @keyword.export for js

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/alpha.lua
- lua/catppuccin/init.lua
- vim.yml
Hi :wave:,
I am using [alpha-vim](https://github.com/goolord/alpha-nvim)  extension. Specifically the way [LazyVim](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/ui.lua#L267-L275) has configured it
I wanted to add the catppuccin theme to it, else it was all white.
This is what it looks like: 
Open to feedback thanks!
> feat(alpha): add support for it

- lua/catppuccin/lib/compiler.lua
- lua/catppuccin/lib/vim/compiler.lua
Thanks so much for all the work on the Neovim theme!
Here's a slight improvement that sets the `g:colors_name` whenever you do `:colorscheme catppuccin-<variant>`. Some reasons why you'd want this:
- When using `:Telescope colorschemes` to select a variant, you can use Telescope again and the same variant will be selected.
- You might have a config that persists color schemes for the next Neovim startup. (this is what I do!)
> feat(colorschemes)!: persist g:colors_name in colorschemes

- lua/catppuccin/groups/integrations/dashboard.lua
Hi, dashboard-nvim now have a new theme called hyper https://github.com/catppuccin/nvim/compare/main...fecet:nvim:feat/dashboard-hyper?expand=1, 
With reference to the original themes of Alpha and Dashboard, I have created this one.
Any input is highly appreciated.
> add group for dashboard hyper theme

- lua/catppuccin/groups/editor.lua
- lua/catppuccin/groups/integrations/neotree.lua
> fix(editor): add FloatTitle hl

- lua/catppuccin/groups/editor.lua
Resolves a conflict between `catppuccin`'s transparent mode and `neo-tree` where `neo-tree`'s fuzzy search would have an invisible `CursorLine`, making it hard to know which item is being selected.
> fix: make `CursorLine` visible for `transparent_background`

- lua/catppuccin/groups/integrations/semantic_tokens.lua
- lua/catppuccin/groups/integrations/treesitter.lua
@Jint-lzxy I cherry picked some changes from https://github.com/catppuccin/nvim/pull/481 that we can all agree on, part 1.
> refactor(syntax): respect editor style guide

- lua/catppuccin/groups/integrations/headlines.lua
- lua/catppuccin/groups/integrations/markdown.lua
- lua/catppuccin/groups/integrations/treesitter.lua
- lua/catppuccin/groups/syntax.lua
Close #492 
Colors taken from [catppuccin style guide rainbow highlights](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#--------------rainbow-highlights--------------brackets-headings-etc------------)
> feat(markdown): add rainbow headlines

- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
This PR adds type annotations which are most useful when combined with [neodev.nvim](https://github.com/folke/neodev.nvim).
I've only added minimal annotations so that the config that the user interacts with is typed.
> feat(types): add type annotations

- README.md
fixes typo wrt fidget.nvim setting — it looks like a copy-paste-o from the row above.
> fix typo wrt fidget.nvim setting

- README.md
as per the docs, colorschemes should be eager-loaded loaded with higher than default priority
> Only useful for start plugins (lazy=false) to force loading certain plugins first. Default priority is 50. It's recommended to set this to a high number for colorschemes.
- https://github.com/folke/lazy.nvim#-plugin-spec
> docs: fix lazy.nvim install method

- lua/catppuccin/groups/integrations/feline.lua
> fix(feline): disable lsp status on nightly

- lua/catppuccin/groups/integrations/native_lsp.lua
The former commit links `Comment` to `LspInalyHint`,
I think the foreground color is very proper to use,
but there is a problem,
catppuccin allows users to customize styles of comments and keywords, 
if the style of comment was set to italic, which is very commonly used,
style of `LspInlayHint` would be italic too.
In addition, in order to make the background color of `LspInlayHint` lighter than
the basic background color for distinction (vscode also does this),
I recommend using the background color of `CursorLine`.
> fix(lsp): do not link `LspInlayHint` to `Comment` directly

- lua/catppuccin/groups/integrations/semantic_tokens.lua
Add few/missing LSP Semantic Tokens: 
* `@lsp.type.boolean`
* `@lsp.type.builtinType`
* `@lsp.type.number`
* `@lsp.type.typeAlias`
* `@lsp.type.unresolvedReference`
* `@lsp.typemod.class.defaultLibrary`
> feat(semantic_tokens): add some lsp semantic tokens

- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/telescope.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
- vim.yml
Updates the Telescope integration to allow users to choose a telescope style between "nvchad" and "classic". 
The default style currently is set to "classic"
- Classic (the original style):
- Nvchad (flat style)
> feat(telescope): telescope flat style support

- lua/catppuccin/groups/integrations/treesitter_context.lua
Updates the Treesitter Context plugin to use a transparent background if transparent_background was set.
> fix(treesitter_context): underline content if `transparent_background` is true

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/native_lsp.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
- vim.yml
> Revert "feat(native_lsp): add ability to disable background for inlay hints"

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/native_lsp.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
- vim.yml
Fixes #523 
The error seems to be due to boolean logic in `native_lsp.lua`:
```diff
-			bg = O.transparent_background and C.none
+			bg = O.transparent_background
+				or not inlay_hints.background and C.none
```
Since `and` has priority over `or`, Lua computes `not inlay_hints.background and C.none` first, and then `O.transparent_background` or'd with the result of `and`. 
Then, if `O.transparent_background` is true (which is the case for me), the `bg` field is set to true, which causes the "invalid 'bg'" error.
Surrounding the `or` statement with parens seemed to solve the issue for me.
> fix(native_lsp): boolean logic

- lua/catppuccin/lib/mapper.lua
- vim.yml
This uses Lua's environment features in order to modify global scope for loading hlgroups instead of the old hacky solution which modified `_G`.
> fix(mapper): remove unnecessary globals

- lua/catppuccin/groups/integrations/navic.lua
- lua/catppuccin/groups/integrations/telescope.lua
- lua/catppuccin/init.lua
- lua/catppuccin/lib/mapper.lua
Both of these configs are valid:
<table>
<tr>
<td> Boolean </td> <td> Table </td>
</tr>
<tr>
<td>
```lua
integrations = {
navic = true,
telescope = true,
dropbar = true,
},
```
</td>
<td>
```lua
integrations = {
navic = {
enabled = true,
custom_bg = "lualine",
},
telescope = {
enabled = true,
style = "nvchad",
},
dropbar = {
enabled = true,
color_mode = true,
},
},
```
</td>
</tr>
</table>
> feat(integrations): accept both boolean and table config

- lua/catppuccin/types.lua
Adds more explicit docs to the `types.lua` file, and adds all the integrations that were missing from the `integrations` table.
> docs: update types

- lua/catppuccin/groups/integrations/telescope.lua
Credit: [ayamir/nvimdots](https://github.com/ayamir/nvimdots/blob/99bc229cf688fab95eb8c48e6ff260c3287b7950/lua/modules/configs/ui/catppuccin.lua#L150)
cc @vollowx @axieax
`results_title = false`
`results_title = true`
`results_title = false`
`results_title = true`
> feat(telescope): make nvchad style great again

- lua/catppuccin/groups/editor.lua
This fixes an issue where certain colors were being overrided in selection menus. In my case this was interferring with plugins like [tailwindcss-colorizer-cmp.nvim](https://github.com/roobert/tailwindcss-colorizer-cmp.nvim) and [cmp-tailwind-colors](https://github.com/js-everts/cmp-tailwind-colors).
A lot of other colorscheme plugins like tokyonight don't set the fg color for `PmenuSel`, so I'd assume this shouldn't cause problems, but please let me know if this was actually intentional.
Before:
After:
> fix: don't highlight fg of `PmenuSel`

- README.md
- doc/catppuccin.txt
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
This adds a new configuration option that allows the user to easily enable/disable all of the included integrations by default.
> feat: add ability to enable/disable all integrations by default

- lua/catppuccin/init.lua
> fix(integration_default): override `enabled` key only if integration has one

- lua/catppuccin/groups/integrations/gitsigns.lua
I found that the fg color of `GitSignsCurrentLineBlame` and `Comment` are the same, which sometimes confuses me:
The Comment fg color is `overlay0` now:
https://github.com/catppuccin/nvim/blob/dae42a0abe01b2f3e3029f203866c6673099745a/lua/catppuccin/groups/syntax.lua#L5
`GitSignsCurrentLineBlame` is mapped to `NonText`:
https://github.com/lewis6991/gitsigns.nvim/blob/749267aaa863c30d721c9913699c5d94e0c07dd3/lua/gitsigns/highlight.lua#L174
And, `NonText` fg color is same with `Comment`:
https://github.com/catppuccin/nvim/blob/dae42a0abe01b2f3e3029f203866c6673099745a/lua/catppuccin/groups/editor.lua#L30
This PR distinguishes the two, making the `GitSignsCurrentLineBlame` dimmer and making it easier to distinguish between the two.
* before
* after
* before
* after
* before
* after
* before
* …
> feat(gitsigns): support GitSignsCurrentLineBlame highlights

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/window_picker.lua
- lua/catppuccin/types.lua
- vim.yml
This adds integration for [nvim-window-picker](https://github.com/s1n7ax/nvim-window-picker). It is used by `neo-tree` and they recently added the ability to configure the colors through highlight groups.
> Add `nvim-window-picker` integration

- lua/catppuccin/groups/integrations/window_picker.lua
Fixes errors raised when using the integration provided in #566.
> Fix missing table keys in nvim-window-picker integration

- lua/catppuccin/groups/integrations/treesitter_context.lua
The only effect of the former treesitter-context support is to add a border-bottom when the `transparent_background` is on.
This PR adds two highlights for normal background, one for a looming border-bottom, and one for the line number.
Former:
Current:
NOTE: The `TreesitterContextLineNumber` should not be configured in catppuccin because the nvim-treesitter-context provided an option to decide whether accept this highlight.
> feat(treesitter-context): add color for normal background

- lua/catppuccin/groups/integrations/aerial.lua
- lua/catppuccin/groups/integrations/lsp_saga.lua
- lua/catppuccin/groups/integrations/treesitter.lua
- lua/catppuccin/groups/syntax.lua
> feat(syntax): respect style guide part 3

- lua/catppuccin/groups/integrations/octo.lua
- Fix type for yellow definition.
- Drop `OctoEditable` group and allow treesitter colors to be shown
Treesitter colors are overwritten if `OctoEditable` by catppuccin.
I tried adding a custom option on the integration, but it would create a breaking change on the config and I don't think is worth the complexity.
See https://github.com/pwntester/octo.nvim/discussions/424 for details on the problem.
> Octo updates

- README.md
- lua/catppuccin/groups/integrations/mini.lua
- lua/catppuccin/types.lua
- vim.yml
Added feature to let users choose what color they want for their scope indent line.
#585 but for mini's indentscope
> feat(mini.indentscope): add scope color

- lua/catppuccin/utils/lualine.lua
other modes share the colors for bg and fg:
- <img width="391" alt="image" src="https://github.com/catppuccin/nvim/assets/385877/58f3a6ef-21d1-4cb9-9436-9d6881dfcd20">
- <img width="396" alt="image" src="https://github.com/catppuccin/nvim/assets/385877/24601f12-d0a9-4aa5-9b2e-398c561e2718">
this just updates the two green modes to match
before
after
> fix(lualine): match lualine mode colors for insert and terminal

- lua/catppuccin/groups/integrations/noice.lua
> fix(noice): respect transparency

- lua/catppuccin/groups/integrations/treesitter.lua
nvim-treesitter may be updated soon, still in discussion but it is planned, see https://github.com/nvim-treesitter/nvim-treesitter/issues/4799#issuecomment-1860154411. The purpose is to follow the treesitter common core to share queries, so some captures will be redefined.
I created this PR to follow upstream changes to avoid highlights break by the breaking change.
There are some highlights defined in treesitter common core but not mentioned in nvim-treesitter
- `@carriage-return`
- `@comment.documentation`
- `@embedded`
- `@escape`
- `@markup.link`
- `@markup.quote`
- `@property.builtin`
- `@variable.member`
And not sure all helix captures will be applied. This PR only follow the common core, need to continue to follow the implementation.
> feat(treesitter): follow upstream captures

- lua/catppuccin/groups/integrations/NormalNvim.lua
- lua/catppuccin/groups/integrations/treesitter.lua
- lua/catppuccin/groups/syntax.lua
Previously, there was no distinction between the colors of `@comment.todo` and `@comment.warn.` The reason is that the color of the warning and the color of the todo are both yellow. I suggest changing the color of the todo to a slightly different color.
> feat: use a more distinguishable color for todos

- lua/catppuccin/groups/integrations/dropbar.lua
Fix a typo in highlight link `DropBarKindIconKeyword` -> `DropBarIconKindKeyword`
> fix(dropbar): correct keyword highlight link

- lua/catppuccin/palettes/init.lua
Fix for #657 (Wrong color shown when using color_overrides in Kitty).
Rewrote this section of code to increment or decrement just the blue channel instead of treating color as a single number.
> fix: wrong color shown when using color_overrides

- lua/catppuccin/groups/integrations/treesitter.lua
> fix: ensure consistency between JSX and HTML markup

- lua/catppuccin/groups/integrations/treesitter.lua
> fix: repair treesitter underlined text (`Underline` -> `Underlined`)

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/treesitter.lua
- lua/catppuccin/types.lua
Set everything to `O.styles.conditionals or { "italic" }`, so, by default, the various settings are still italic. In other words, this is not a breaking change.
🎉 First off, thanks for taking the time to contribute! 🎉
Here are some guidelines:
- New plugin integration should be added in alphabetical order:
- to the [README](https://github.com/catppuccin/nvim#integrations) (vimdoc is auto-generated).
- to [types.lua](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/types.lua)
- Use [conventionalcommits.org's](https://www.conventionalcommits.org/en/v1.0.0/)
rules for explicit and meaningful commit messages.
- If it's your first time contributing to a …
> feat(treesitter): add styles.miscs to disable hardcoded italics

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/feline.lua
This PR adds the option to changes the "Lsp" text to the actual name of the connected lsp servers.
It also adds the option to disable the lsp progress indicator. 
The reason for this is that there are other solutions to display the progress indicator which work better.
Old:
New:
> feat(feline): improve feline lsp display

- autoload/airline/themes/catppuccin.vim
Hello, first off, this is my first PR ever, so sorry in advance if not everything is up to standard, I tried to follow every information i could find.
The purpose of this PR is to fix some errors with the Airline integration. I know there is also support for Lualine, but i haven't personally made that switch yet.
For some reason, section B of Airline (second from the left, where i.e. Git branch is displayed) is styled exactly the same before as section C (Filename). By changing the background color, it looks much better. This is the same color that is used in Lualine for this purpose.
I don't know if anyone uses replace mode not out of accident, but I noticed the colors for warning & error section were not applied in that mode. I changed this to match all the other modes by defining …
> Refresh airline colors

- lua/catppuccin/groups/integrations/native_lsp.lua
Otherwise, the color of the separator will be `Normal`, which is ugly because code lenses have a color like `Comment`.
Before:
After:
> feat(lsp): add highlight for `LspCodeLensSeparator`

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/colorful_winsep.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
https://github.com/nvim-zh/colorful-winsep.nvim
> feat(integration): add colorful-winsep.nvim

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/diffview.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
Added integration for [diffview.nvim](https://github.com/sindrets/diffview.nvim)
Before
After
> feat(diffview): add diffview integrations

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/native_lsp.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
This diagnostic type was introduced with Neovim 0.10, and, as far as I can tell,
they are only used in `:checkhealth` for now.
I believe teal may be closer to the color used in the (new) default theme, but
that color is already used for hints, so I just used green instead.
I did not add this was not added to the "LspDiagnostic\*" highlights since I
could not find any documentation on whether the "Ok" diagnostic is implemented
for those. Indeed, I could not find any documentation whatsoever on the
LspDiagnostic\* highlights (grepping the Neovim source turned up no mentions of
them either). It may be worth removing those highlights altogether if they don't
show up anywhere. Furthermore, the Diagnostic highlights should be moved to
their own module, since they are an independent mechanism …
> Support new "Ok" diagnostics

- lua/catppuccin/groups/integrations/neogit.lua
> fix(neogit): link WinSeparator

- lua/catppuccin/init.lua
The documentation says that mini is enabled by default, but it is not. This patch changes the defaults to match what is documented.
https://github.com/catppuccin/nvim/blob/cc8e290d4c0d572171243087f8541e49be2c8764/README.md?plain=1#L880-L885
Closes #715
> fix(defaults): Enable mini integration by default

- lua/catppuccin/groups/integrations/mini.lua
Add explicit support for all new groups since #166 and for the (hopefully) upcoming 'mini.icons'.
> feat(mini): add new highlight groups

- lua/catppuccin/groups/editor.lua
This PR simply give `FloatBorder` highlight the same background as `NormalFloat`, which fixes up the `solid` window border option (that border was colored as `base`, looked strange and ugly).
> fix: color float window border background

- lua/catppuccin/groups/integrations/dap_ui.lua
Simple change following 31fcfb0
Before:
After:
> fix(dapui): border match bg color

- lua/catppuccin/groups/integrations/leap.lua
Changes in https://github.com/ggandor/leap.nvim/commit/b75a86f14ebdb3940460bfd1a02224210eccc698 causes leap to not highlight labels found by leap.
This PR fixes it by removing `LeapLabelSecondary` and replacing `LeapLabelPrimary` with `LeapLabel`
> fix(leap): highlight group for `LeapLabel`

- lua/catppuccin/groups/integrations/feline.lua
Add option to show how many plugin updates has lazy.nvim in feline.
The code already checks if lazy.nvim is installed. If so, then the updates appears as a number with the package icon.
It looks like this:
> feat(feline): add lazy.nvim updates module, replace deprecated API

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/feline.lua
This PR added an option to hide the count of updatable plugins from lazy.nvim, and updated the documentations for feline.nvim.
Please check this out @ilias777 :eyes:
> feat(feline): allow to hide lazy.nvim updates

- README.md
- lua/catppuccin/groups/integrations/nvim_surround.lua
- lua/catppuccin/types.lua
This is to distinguish the document highlight of LSP. NvimSurroundHighlight is linked to Visual by default, so they both have the same background color 'surface1'.
NOTE: Sometimes, LspReferenceXxxx (document highlight) color may override the NvimSurroundHighlight. I have no idea how to fix that,  need somebody to help.
Snapshot:
> feat(nvim-surround): add integration

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/grug_far.lua
- lua/catppuccin/types.lua
This adds support for [grug-far.nvim](https://github.com/MagicDuck/grug-far.nvim). Most of the highlights are solid choices out of the box, but this one should be made more visible.
> feat: add `grug-far.nvim` integration

- lua/catppuccin/groups/integrations/treesitter.lua
> fix(treesitter): highlight paths in `.gitignore` as text

- README.md
- lua/catppuccin/groups/integrations/render_markdown.lua
The repository has been renamed: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/aeb5cec617c3bd5738ab82ba2c3f9ccdc27656c2
> docs: rename markdown.nvim to render-markdown.nvim

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/lir.lua
- lua/catppuccin/types.lua
highlights used by [lir.nvim](https://github.com/tamago324/lir.nvim) and it's [lir-git-status.nvim](https://github.com/tamago324/lir-git-status.nvim) extension.
> feat: add lir.nvim and lir-git-status.nvim integration

- lua/catppuccin/groups/integrations/render_markdown.lua
Fixed an issue where the `integrations.native_lsp.virtual_text` style was being applied to callouts (italic by default).
before:
after:
> feat(render-markdown): add highlights for callouts

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/fzf.lua
- lua/catppuccin/types.lua
> feat: add fzf-lua integration

- lua/catppuccin/groups/editor.lua
Closes #737 
cc @u0398 
Currently: `TermCursor fg=base,bg=red` `TermCursorNC fg=base,bg=overlay2`
> feat(terminal): highlight `TermCursor` and `TermCursorNC`

- lua/catppuccin/groups/editor.lua
> Revert "feat(terminal): highlight `TermCursor` and `TermCursorNC`"

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/dadbod_ui.lua
- lua/catppuccin/types.lua
Summary
----
This adds support for [dadbod-ui](https://github.com/kristijanhusak/vim-dadbod-ui).
I chose the following colors (mostly because it seemed reasonable):
```
NotificationInfo = { fg = C.blue, bg = C.mantle },
NotificationWarning = { fg = C.yellow, bg = C.mantle },
NotificationError = { fg = C.red, bg = C.mantle },
```
PS: There's some whitespace cleanup here as well.
> feat: add vim-dadbod-ui integration

- lua/catppuccin/groups/editor.lua
It looks like `TabLineFill` background got removed at some point. This adds it back in
> fix(editor): add missing background for `TabLineFill`

- lua/catppuccin/groups/editor.lua
Hello!
Currently, the `TabLine` foreground is too dark, barely readable with an even darker background:
After:
> fix(editor): make TabLine more readable

- lua/catppuccin/groups/syntax.lua
Teeny change from overlay0 to overlay2 for comments to match the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors).
> fix(syntax): use `overlay2` for comments

- lua/catppuccin/groups/integrations/colorful_winsep.lua
The background color should be transparent ('none') if config option is set.
> fix(colorful-winsep): respect transparent_background configuration

- lua/catppuccin/groups/integrations/render_markdown.lua
Although this may seem like a very subjective change, it is not. There's two reasons:
1. render-markdown itself uses a similar color in its README like:
2. neovim's `vim.lsp.buf.hover` uses markdown to render colors, so the colder blocks should be better to use the same color with `NormalFloat`, otherwise the color is awful:
* before: ![image](https://github.com/user-attachments/assets/6261f62c-8397-431f-8e37-4fd0c4e67b36)
* after: ![image](https://github.com/user-attachments/assets/2656efe3-38d5-4f07-9bd9-65af9f785d09)
> feat(render-markdown): change code block background to `mantle`

- lua/catppuccin/groups/editor.lua
As discussed in https://github.com/catppuccin/nvim/pull/760#pullrequestreview-2239840349
Before:
After:
> fix(editor): more "modern" tabline

- lua/catppuccin/groups/integrations/native_lsp.lua
I used surface1 as the color, the same as those used by LspReferenceText, LspReferenceRead, and LspReferenceWrite.
This change helps to highlight the current parameter under the cursor when invoking `vim.lsp.buf.signature_help`.
`name: string` has a peach foreground but the same background as the other parameters, making it hard to distinguish.
`name: string` has a peach foreground and a surface1 background, making distinguishing from the other parameters easier.
> feat: add background highlight to LSP signature help

- lua/catppuccin/groups/integrations/dap_ui.lua
`nvim-dap-ui` has highlight groups for all its buttons: `DapUIPlayPause`, `DapUIStepOver`, etc. But it also has `*NC` versions of those highlights. I assume NC stands for non-current or "no cursor".
`nvim-dap-ui` defaults to linking those to their non-`*NC` versions but I assume it happens too early and Catppuccin does not pick that up. This PR simply duplicates the highlight groups to include `*NC` versions.
See https://github.com/rcarriga/nvim-dap-ui/blob/ffa89839f97bad360e78428d5c740fdad9a0ff02/lua/dapui/config/highlights.lua#L75-L96
> fix(dap-ui): add colors for *NC hlgroups of UI controls

- README.md
Document neotree as being an integration that is active by default.
ref: [#c536623](https://github.com/catppuccin/nvim/commit/c536623eac60f8443c93ae4ca0e03b51574b5f50)
> docs(integrations): reflect that `neotree` is enabled by default

- lua/catppuccin/groups/integrations/blink_cmp.lua
Closes #797 .
_Shadow comes from Neovide_
@giuxtaposition We've decided to prioritize the default UI over the bordered one, and the ones who likes it bordered need to override the highlights by themselves now.
> fix(blink-cmp): follow `Pmenu` highlights

- lua/catppuccin/groups/integrations/blink_cmp.lua
This PR adds the blink cmp matching highlight group
Source:
https://github.com/Saghen/blink.cmp/blob/6516736e15eb0ca0120df2dc11528cb2d257092e/README.md?plain=1#L144
I copied the styling from the nvim-cmp integration
https://github.com/catppuccin/nvim/blob/35d8057137af463c9f41f169539e9b190d57d269/lua/catppuccin/groups/integrations/cmp.lua#L9C57-L9C58
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> feat(blink-cmp): support `BlinkCmpLabelMatch` hl

- README.md
- lua/catppuccin/groups/integrations/copilot_vim.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
Adding [Github's oficial copilot.nvim repo](https://github.com/github/copilot.vim).
> feat(copilot): add integration

- lua/catppuccin/groups/integrations/nvim_surround.lua
nvim-surround highlight is sometimes covered by document highlight, so using underline to resolve the conflict.
before:
after:
> fix(nvim-surround): bg conflicts with document highlight

- README.md
- lua/catppuccin/groups/integrations/snacks.lua
- lua/catppuccin/types.lua
Adds [`snacks.nvim`](https://github.com/folke/snacks.nvim) integration to Catppuccin.
Closes #806
> feat(snacks): add integration

- lua/catppuccin/groups/integrations/fzf.lua
The background color doesn't match the border, making it inconsistent. The title is now consistent with telescope too.
Before
After
> fix: match fzf-lua highlights to telescope

- lua/catppuccin/groups/integrations/gitsigns.lua
This PR aims to improve the colors of changed text when running `:Gitsigns preview_hunk` with `transparent_background = false` (see the screenshot below).
For the dark themes, the cursor color seems to "conflict" with the diff colors, making it hard to track the cursor if focusing a hunk and, e.g., copying some text.
For `GitSignsAddInline`, it took the color of https://github.com/catppuccin/nvim/blob/faf15ab0201b564b6368ffa47b56feefc92ce3f4/lua/catppuccin/groups/syntax.lua#L73 and doubled the amount from `18` to `36`. I did the same with `GitSignsDeleteInline` and https://github.com/catppuccin/nvim/blob/faf15ab0201b564b6368ffa47b56feefc92ce3f4/lua/catppuccin/groups/syntax.lua#L75
> feat(gitsign): improve gitsign inline add and delete colors

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/gitgraph.lua
- lua/catppuccin/types.lua
🎉 First off, thanks for taking the time to contribute! 🎉
Here are some guidelines:
- New plugin integration should be added in alphabetical order:
- to the [README](https://github.com/catppuccin/nvim#integrations) (vimdoc is auto-generated).
- to [types.lua](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/types.lua)
- Use [conventionalcommits.org's](https://www.conventionalcommits.org/en/v1.0.0/)
rules for explicit and meaningful commit messages.
- If it's your first time contributing to a project, then read
[About pull requests](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about …
> Add `gitgraph.nvim`

- README.md
`girgraph` integration is disabled by default in #822, but `gitgraph = true` in README.md
> fix(gitgraph): readme `gitgraph` default 

- lua/catppuccin/groups/integrations/avante.lua
- lua/catppuccin/types.lua
Adding support for [avante](https://github.com/yetone/avante.nvim). I'm open to changing what colors are used on the titles, I'm not sure if we have a convention for that.
Sidebar colors:
Inline text
If rounded is turned off
> feat: add Avante integration

- README.md
- lua/catppuccin/groups/integrations/snacks.lua
- lua/catppuccin/types.lua
This PR adds the `SnacksIndent` and `SnacksIndentScope` highlight groups to the snacks integration.
I mainly just copied the indent-blankline integration for this haha
[Relevant docs from snacks.nvim repo](https://github.com/folke/snacks.nvim/blob/main/docs/indent.md)
> feat(snacks): add indent highlights

- README.md
> fix feline lua syntax error in README.md

- README.md
- lua/catppuccin/groups/integrations/gitsigns.lua
- lua/catppuccin/types.lua
This PR complements https://github.com/catppuccin/nvim/pull/826
1. Update types.lua and README.md
2. Set `gitsigns.transparent` to align with `transparent_background` by default
3. Optimize certain display effects as shown in the screenshots below
before:
after:
Hi @heddxh, this PR should address the issue you mentioned in https://github.com/catppuccin/nvim/pull/826#issuecomment-2692299645. Would you mind testing it?
> fix(gitsigns): respect transparent option for gitsigns

- lua/catppuccin/groups/integrations/markview.lua
- lua/catppuccin/groups/integrations/render_markdown.lua
use crust as a darkening background for markdown headings with transparent background. previously would fall back to `#000000` (`nil`) which does not work well for latte.
fixes #845 
BEGIN_COMMIT_OVERRIDE
fix(markview): incorrect heading bg when using transparent bg
fix(render-markdown): incorrect heading bg when using transparent bg
END_COMMIT_OVERRIDE
> fix: transparent markdown headings bg

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/blink_cmp.lua
- lua/catppuccin/types.lua
adds a `style` to configure whether to use bordered or solid borders. 
can in a future pr be used to add atom-like pmenu styling.
Closes #809
> feat(blink-cmp): add `style` option

- lua/catppuccin/lib/detect_integrations.lua
The new auto integration detection is great! I noticed in some cases it doesn't enable the integration unless I manually put `enabled = true` in the integrations table. I dug into this and it appears it's missing the portion that sets `enabled = true` for table based integration configuration.
The example I ran into this with was setting up custom configuration for `snacks = { picker_style = "nvchad" }` in my integrations table and the snacks integration is not properly enabled when I start the editor. It simply needs `enabled = true` enabled. This will also be the case for something like `colorful_winsep` or `navic` where the default configuration has `enabled = false`
> fix: make sure to enable auto detected integrations with table configurations

- lua/catppuccin/init.lua
Based on how the auto integration is done, plugins with table based configuration are required to have them specified in the default integration list to actually make auto integration detection work if the user has done any sort of customization to the integrations.
For example if the `snacks` is set to `{ picker_style = "nvchad" }` then without this change the auto integration detection doesn't work. This is because the auto detection would set `snacks = true` and then would not merge properly with the user configuration table, so the result is just `{ picker_style = "nvchad" }` rather than `{ enabled = true, picker_style = "nvchad" }`
This is a follow on to #886
> fix: add missing table based integrations to fix auto integration detection

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/editor.lua
- lua/catppuccin/groups/integrations/mini.lua
- lua/catppuccin/groups/integrations/snacks.lua
- lua/catppuccin/groups/integrations/telescope.lua
- lua/catppuccin/init.lua
- lua/catppuccin/types.lua
fixes #856
based on the work started in #877
putting all the floating window options, that were previously in integration opts, globally so its clear what integrations should provide in customization:
```lua
-- config:
{
float = {
transparent = false, -- whether floating windows should be transparent
solid = false, -- whether to use nvchad (solid) style or classic style floats
},
}
```
in the current implementation i would get the following results for `transparent_background = true`:
trans bg + trans float + classic float = outlined
trans bg + opague float + solid float = nvchad
trans bg + trans float + solid float = nvchad outlined
> feat!: add global floating window options

- lua/catppuccin/groups/editor.lua
- lua/catppuccin/groups/integrations/blink_cmp.lua
bring the current pmenu styling to be more in line with the current vscode style
this change is based on the personal preferences of the maintainers of this project. it has nothing to do with the popularity of vscode :)
> feat(editor): align pmenu styling with vscode

- README.md
- doc/catppuccin.txt
- lua/catppuccin/groups/integrations/bufferline.lua
- lua/catppuccin/groups/integrations/feline.lua
- lua/catppuccin/lib/mapper.lua
- **fix(lib/mapper): allow for integrations without `get()` field**
- **fix(integrations/feline): rename `get()` to `get_statusline()`**
- **fix(integrations/bufferline): rename `get()` to `get_theme()`**
theres an issue where some integrations should never be able to get enabled through the config options: if they do it will error because the returned value will be assumed to be a highlights table. this will obviously cause issues when the returned value is not meant to be passed to `vim.api.nvim_set_hl()`, like with feline and bufferline.
this issue is occuring because the `auto_integrations` enables these special integrations if the plugin is detected.
> fix(integrations)!: rename `get()` to `get_*()` on abnormal integrations

- lua/catppuccin/types.lua
All other config fields are optional (or explicitly nil). This field technically is also optional. The PR matches code and types.
The other fields that are not optional are sub-fields found in classes (of optional fields)
<details><summary>Why I made this PR</summary>
<p>
In my personal config, I keep getting the following warning:
```
1. Missing required fields in type `CatppuccinOptions`: `float` [missing-fields]
```
Config for context:
```lua
{
-- Theme
"catppuccin/nvim",
name = "catppuccin",
priority = 1000,
config = function()
require("catppuccin").setup({
auto_integrations = true,
flavour = "mocha"
})
vim.cmd.colorscheme "catppuccin"
end,
}
```
Simple enough fix for a simple enough annoyance.
</p>
</details>
> fix: config `float` is optional in setup
